name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Build Directory
        run: |
          cd Argon
          mkdir build

      - name: Configure CMake
        run: |
          cd Argon
          cmake -S . -B build

      - name: Build
        run: |
          cd Argon/build
          cmake --build build

      - name: Test (optional)
        run: |
          cd Argon/build
          ctest
